using Toybox.Graphics as Gfx;

module Globals {
	const METERS_IN_MILE = 1609.34f;
	const CENTER = Gfx.TEXT_JUSTIFY_CENTER;
	const VCENTER = Gfx.TEXT_JUSTIFY_CENTER | Gfx.TEXT_JUSTIFY_VCENTER;
	const LEFT = Gfx.TEXT_JUSTIFY_LEFT;
	const LEFT_VCENTER = Gfx.TEXT_JUSTIFY_LEFT | Gfx.TEXT_JUSTIFY_VCENTER;
	const ZERO_TIME = "0:00";
	const ZERO_DISTANCE = "0.00";
}