module Globals {
	enum {
		HEART_RATE_MODE_CURRENT,
		HEART_RATE_MODE_AVERAGE,
		HEART_RATE_MODE_3_SECONDS,
		HEART_RATE_MODE_5_SECONDS,
		HEART_RATE_MODE_10_SECONDS,
		HEART_RATE_MODE_30_SECONDS
	}
}